source: .
destination: ./_site
encoding: utf-8
include: [
  'assets'
]
exclude: [
  'node_modules',
  'src',
  'npm-debug.log',
  'package.json',
  'README.md',
  'webpack.config.babel.js'
]
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
